import Head from 'next/head'
import Link from 'next/link'
import {getAllPosts, getAllTags, getPostsFourTopPage} from '../lib/notionAPI';
import SinglePost from '../components/Post/SinglePost';
import Tag from '../components/Tag/Tag';

export const getStaticProps = async () => {
  const fourPosts = await getPostsFourTopPage();
  const tags = await getAllTags();
  return {
    props: {
      fourPosts,
      tags,
    },
    revalidate: 60 * 60 * 6,
  }
}

export default function Home({fourPosts, tags}) {
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion-blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium text-center mb-16">
          Notion Blog
        </h1>
        {fourPosts.map((post) => (
          <div className="mx-4" key={post.id}>
            <SinglePost
              title={post.title}
              description={post.description}
              date={post.date}
              tags={post.tags}
              slug={post.slug}
              isPaginationPage={false}
            />
          </div>
        ))}
        <Link href="/posts/page/1" className="mb-6 lg:w-1/2 mx-auto px-5 block text-right text-sky-900">...more</Link>
        <Tag tags={tags} />
      </main>
    </div>
  )
}
